<script setup lang="ts">

</script>


  
<template>

  <section class="padding"><section id="products" class="max-container max-sm:mt-12"><div class="flex flex-col justify-start gap-5"><h2 class="text-4xl font-palanquin font-bold">Our <span class="text-coral-red"> Popular </span> Products</h2><p class="lg:max-w-lg mt-2 font-montserrat text-slate-gray">Experience top-notch quality and style with our sought-after selections. Discover a world of comfort, design, and value</p></div><div class="mt-16 grid lg:grid-cols-4 md:grid-cols-3 sm:grid-cols-2 grid-cols-1 sm:gap-6 gap-14"><div class="flex flex-1 flex-col w-full max-sm:w-full"><img src="/src/assets/images/shoe4.svg" alt="Adidas Air Jordan-01" class="w-[282px] h-[282px]"><div class="mt-8 flex justify-start gap-2.5"><img src="/src/assets/icons/star.svg" alt="rating icon" width="24" height="24"><p class="font-montserrat text-xl leading-normal text-slate-gray">(4.5)</p></div><h3 class="mt-2 text-2xl leading-normal font-semibold font-palanquin">Adidas Air Jordan-01</h3><p class="mt-2 font-semibold font-montserrat text-coral-red text-2xl leading-normal">$200.20</p></div><div class="flex flex-1 flex-col w-full max-sm:w-full"><img src="/src/assets/images/shoe5.svg" alt="Adidas Air Jordan-10" class="w-[282px] h-[282px]"><div class="mt-8 flex justify-start gap-2.5"><img src="/src/assets/icons/star.svg" alt="rating icon" width="24" height="24"><p class="font-montserrat text-xl leading-normal text-slate-gray">(4.5)</p></div><h3 class="mt-2 text-2xl leading-normal font-semibold font-palanquin">Adidas Air Jordan-10</h3><p class="mt-2 font-semibold font-montserrat text-coral-red text-2xl leading-normal">$210.20</p></div><div class="flex flex-1 flex-col w-full max-sm:w-full"><img src="/src/assets/images/shoe6.svg" alt="Adidas Air Jordan-100" class="w-[282px] h-[282px]"><div class="mt-8 flex justify-start gap-2.5"><img src="/src/assets/icons/star.svg" alt="rating icon" width="24" height="24"><p class="font-montserrat text-xl leading-normal text-slate-gray">(4.5)</p></div><h3 class="mt-2 text-2xl leading-normal font-semibold font-palanquin">Adidas Air Jordan-100</h3><p class="mt-2 font-semibold font-montserrat text-coral-red text-2xl leading-normal">$220.20</p></div><div class="flex flex-1 flex-col w-full max-sm:w-full"><img src="/src/assets/images/shoe7.svg" alt="Adidas Air Jordan-001" class="w-[282px] h-[282px]"><div class="mt-8 flex justify-start gap-2.5"><img src="/src/assets/icons/star.svg" alt="rating icon" width="24" height="24"><p class="font-montserrat text-xl leading-normal text-slate-gray">(4.5)</p></div><h3 class="mt-2 text-2xl leading-normal font-semibold font-palanquin">Adidas Air Jordan-001</h3><p class="mt-2 font-semibold font-montserrat text-coral-red text-2xl leading-normal">$230.20</p></div></div></section></section>


</template> 
